import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";
import { Spinner } from "@/components/spinner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Spinner of infinite brokeness</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main data-theme="night">
        <div className="flex flex-col h-screen">
          <nav className="navbar bg-base-300 content-center justify-center">
            <div className="flex-1 navbar-start mx-11 self-center">
              <button className="btn  p-x-5 whitespace-nowrap text-xl">
                Spinner of infinite Broke-ness
              </button>
            </div>
          </nav>
          <Spinner />
          <footer className="footer  bg-base-300 content-center justify-center">
            <div className="flex-1 flex w-full navbar-start mx-11 py-2 self-center place-content-between">
              <button className="btn btn-primary p-x-5 whitespace-nowrap text-xl">
                <a href="https://notacult.social/@rboskind">
                  Follow me on Mastodon
                </a>
              </button>
              <button className="btn btn-primary p-x-5 whitespace-nowrap text-xl">
                <a href="https://cassidoo.co/">
                  Cassidoo - The bright idea behind this
                </a>
              </button>
              <button className="btn btn-primary p-x-5 whitespace-nowrap text-xl">
                <a href="https://twitter.com/RobBoskind">
                  Follow me on Twitter
                </a>
              </button>
            </div>
          </footer>
        </div>
      </main>
    </>
  );
}
